### ISSUE TITLE
roll-up for testing and UX issues by kx1t

### ISSUE THREAD

**Issue by kx1t** [fredclausen/sdr-docker-config#46]
This is a quick roll-up of the issues I came across, in no particular order

- fix for standard screen size, or at least trap the `Exception:  addwstr() returned ERR` and show instructions to make the screen bigger
- Install the containers in order of importance rather than alphabetically:
   - first readsb and tar1090
   - then mlathub
   - then the feeder containers
   - then additional accessories like acarshub and planefence
- need good instructions what to collect BEFORE trying to install the container, and where to get these things.
   - @Mikenye's gitbook is good in instructing how to rename SDR serial numbers, where to get feeder creds, etc.
- allow variable values (Lat/Lon/TZ/...) to be reused for other containers once entered. Mike's original instructions were to enter those into a `.env` file and have references to these variables in `docker-compose.yml`
- timezones: they are finicky to enter. Allow the user to "scroll" through available timezones, with the current system TZ selected as default. Similar to what `raspi-config` does
- Consistent in messaging around keys. Sometimes it just asks for one, sometimes it tells you that you can edit the config later, etc.
- Provide instructions for each feeder key on how/where to get them. This is complex, as there will be a mix of current users (existing keys) and new users (generate new keys). My specific concern is that a novice user won't know what to answer and gets stuck on a question
- PiAware: "Would you like to enable ADSB feeding?" -- not sure about this question. Isn't this always YES?
- readsb: "Display values as metric" (Y/N). What's the alternative? Imperial? Aeronautic?
- Radarbox: missing the installation for the segmentation fault fix (see [here](https://mikenye.gitbook.io/ads-b/feeder-containers/feeding-radarbox#segfault-fix))
- keep the config overview and port mappings visible when you exit the configurator
- Install the `docker-compose.yml` file to a standard directory to force good docker habits -- for example, to `/opt/adsb`
- Once the configurator is done, provide instructions on what to do next: `docker-compose up -d`
- Also mentioned by @TC -- use `.yml` extension instead of `.yaml` because most novices have been trained to use that extension

**Comment by fredclausen** [comment]
> * need good instructions what to collect BEFORE trying to install the container, and where to get these things.
>   * @mikenye's gitbook is good in instructing how to rename SDR serial numbers, where to get feeder creds, etc.

While I was running I was thinking about this. I was considering a two step process to alleviate some of the configuration issues that will present themselves with the SDRs

* The as-yet-unwritten wrapper should give the user an explanation about SDR serials, and allow them to re-write the serial
* Any configuration item that wants an SDR serial could have a list of unchosen SDRs. Advanced mode will skip that and let manual input of SDRs

> * allow variable values (Lat/Lon/TZ/...) to be reused for other containers once entered. Mike's original instructions were to enter those into a `.env` file and have references to these variables in `docker-compose.yml`

I briefly considered .env but wrote it off as beyond the scope of this. Maybe I was wrong, and I'll think about it. What I am thinking about is having a 'pre-configuration' section where the plugin will define global values and any container that wants them can refer back to them. I wasn't planning on writing an env file, even with this implementation, but...honestly sounds a lot like a .env file with extra steps, doesn't it? Hmm.

> * timezones: they are finicky to enter. Allow the user to "scroll" through available timezones, with the current system TZ selected as default. Similar to what `raspi-config` does

I agree - I'll look in to how to do this.

> * Consistent in messaging around keys. Sometimes it just asks for one, sometimes it tells you that you can edit the config later, etc.

Yeah, the plugin messaging needs work. It was kind of a 'get something that works, make it better later' thing.

> * Provide instructions for each feeder key on how/where to get them. This is complex, as there will be a mix of current users (existing keys) and new users (generate new keys). My specific concern is that a novice user won't know what to answer and gets stuck on a question

This should be covered on the website. Originally I had the keys for the feeder keys not allow a blank entry, but I realized that was not the right way. Honestly, the 'I've never run an ADSB station before and have no idea what I am doing' is kind of the night-mare situation for this program, because there simply isn't an easy way to get them a user key because most (except for adsb hub iirc) require the feeder to actually RUN. I considered running the container during setup and grabbing the key, but that just sounds complicated, messy, and drags the setup out for too too long - especially since one of the feeders, I forget which one, requires running the feeder for five *minutes* before it'll give a key.

> * PiAware: "Would you like to enable ADSB feeding?" -- not sure about this question. Isn't this always YES?

I just copied the key from Mike's piaware config - I have no idea what the hell it means or why you'd ever say no :) Maybe I should hide it as 'advanced' if I haven't already and just ensure it's enabled by default.

> * readsb: "Display values as metric" (Y/N). What's the alternative? Imperial? Aeronautic?

I believe the alternative is nautical - but I should make it clear what the two choices are.

> * Radarbox: missing the installation for the segmentation fault fix (see [here](https://mikenye.gitbook.io/ads-b/feeder-containers/feeding-radarbox#segfault-fix))

I'll add that in.

> * keep the config overview and port mappings visible when you exit the configurator
> * Install the `docker-compose.yml` file to a standard directory to force good docker habits -- for example, to `/opt/adsb`
> * Once the configurator is done, provide instructions on what to do next: `docker-compose up -d`
> * Also mentioned by @tc -- use `.yml` extension instead of `.yaml` because most novices have been trained to use that extension

Good thoughts - I'll get those sorted.

**Comment by fredclausen** [comment]
- [ ] Screen size fix
- [ ] Container type / sort
- [ ] .env file
- [ ] Timezone smartness
- [ ] yaml (ok yml) file installation to /opt/
- [ ] Use .yml
- [ ] Show exit message even after program exit
- [ ] Show post-installation instructions (ensure to cover the 'need feeder key' stuff)
- [ ] radarbox segfault fix
